source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ISUActionMenu_Example', :exclusive => true do
  pod 'ISUActionMenu', :path => '../'
end

target 'ISUActionMenu_Tests', :exclusive => true do
  pod 'ISUActionMenu', :path => '../'

  
end
